name: dialog_services
version: 1.0.0
description: Package for dialog services
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  shared:
    path: ../shared
  ui:
    path: ../ui

  # DI
  injectable: ^2.1.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code generation
  build_runner: ^2.3.2

  # DI
  injectable_generator: ^2.1.4

