name: ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.6

  # pin code field
  pin_code_fields: ^7.4.0

  cached_network_image: ^3.2.3


  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  # assets generation
  flutter_gen: ^5.3.1

flutter_gen:
  output: lib/src/gen/
  assets:
    outputs:
      package_parameter_enabled: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # generate: true
   # Add this line  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/